[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "STRICT"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = '''
    default-src 'self';

    font-src 'self' fonts.gstatic.com gstatic.com *.gstatic.com;
    img-src 'self' data: *.googleusercontent.com *.arcana.network;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' googletagmanager.com *.googletagmanager.com apis.google.com;
    style-src 'self' 'unsafe-inline' fonts.googleapis.com;
    frame-src 'self' *.arcana.network;

    connect-src 'self' arcana.network *.arcana.network *.arcana.network:9000 google-analytics.com *.google-analytics.com googleapis.com *.googleapis.com list-manage.com *.list-manage.com sentry.io *.sentry.io;

    object-src 'none';'''

[build]
  command = "npm run build"
  publish = "dist"
