[context.production.environment]
  VITE_ARCANA_APP_ID="500"
  VITE_GATEWAY_URL="https://gateway-testnet.arcana.network/"

[context.branch-deploy.environment]
  VITE_ARCANA_APP_ID="17"
  VITE_GATEWAY_URL="https://gateway-dev.arcana.network/"

[context.deploy-preview.environment]
  VITE_ARCANA_APP_ID="17"
  VITE_GATEWAY_URL="https://gateway-dev.arcana.network/"
