[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "STRICT"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
    default-src 'self';

    font-src 'self' fonts.gstatic.com gstatic.com *.gstatic.com;
    img-src 'self' data: *.googleusercontent.com;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' googletagmanager.com *.googletagmanager.com apis.google.com;
    style-src 'self' 'unsafe-inline' fonts.googleapis.com;

    connect-src 'self' arcana.network *.arcana.network google-analytics.com *.google-analytics.com googleapis.com *.googleapis.com list-manage.com *.list-manage.com sentry.io *.sentry.io;

    object-src 'none';'''

[[redirects]]
  from = "/*"
  to = "https://demo.beta.arcana.network/*"
  status = 200
  force = true

